cloudflare:
  secretRef:
    name: cloudflare-api-token
    accountIDKey: accountid
    tunnelNameKey: tunnelname
    apiTokenKey: apitoken


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi