cloudflare:
  secretRef:
    name: cloudflare-api-token
    accountIDKey: account_id
    tunnelNameKey: tunnel_name
    apiTokenKey: api_token


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi