imagePullSecrets: 
  - name: ghcr-token
fullnameOverride: ""

defaults:
  replicaCount: 1
  imagePullPolicy: IfNotPresent
  serviceType: ClusterIP
  servicePort: 80

podSecurityContext: {}
securityContext: {}

sites:
  - name: blog-willberto-biz
    replicaCount: 1
    image:
      repository: ghcr.io/lukeaurio/blog-willberto-biz
      pullPolicy: IfNotPresent
      tag: latest
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      className: "cloudflare-tunnel"
      annotations: {}
      hosts:
        - host: blog.willberto.biz
          paths:
            - path: /
              pathType: Prefix
      tls: []
    podAnnotations: {}
    podLabels: {}
    resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
