name: 'Setup OpenTofu and Lint'
description: 'A composite action to setup and run OpenTofu commands'

inputs:
  tofu_directory:
    description: 'The directory where OpenTofu files are located'
    required: true
    default: '.'

outputs:
  init_stdout:
    description: 'The result of the OpenTofu init command'
    value: ${{ steps.init.outputs.stdout || '' }}
  init_stderr:
    description: 'The stderr of the OpenTofu init command'
    value: ${{ steps.init.outputs.stderr || '' }}
  validate_stdout:
    description: 'The result of the OpenTofu validate command'
    value: ${{ steps.validate.outputs.stdout || '' }}
  validate_stderr:
    description: 'The stderr of the OpenTofu validate command'
    value: ${{ steps.validate.outputs.stderr || '' }}
  plan_stdout:
    description: 'The result of the OpenTofu plan command'
    value: ${{ steps.plan.outputs.stdout || '' }}
  plan_stderr:
    description: 'The stderr of the OpenTofu plan command'
    value: ${{ steps.plan.outputs.stderr || '' }}
  plan_json:
    description: 'The OpenTofu plan in JSON format'
    value: ${{ steps.plan_json.outputs.json || '' }}
  plan_summary:
    description: 'Summary of plan changes'
    value: ${{ steps.parse_plan.outputs.summary || '' }}

runs:
  using: 'composite'
  steps:
    - name: Set Up Opentofu
      uses: opentofu/setup-opentofu@v1

    - name: OpenTofu Init
      id: init
      working-directory: ${{ inputs.tofu_directory }}
      run: tofu init -backend-config="bucket=${{ env.tfstates_bucket }}" -backend-config="prefix=${{ env.tfstates_prefix }}" -input=false -no-color
      shell: bash
      continue-on-error: true

    - name: OpenTofu Validate
      id: validate
      working-directory: ${{ inputs.tofu_directory }}
      run: tofu validate -no-color
      shell: bash
      continue-on-error: true

    - name: OpenTofu Plan
      working-directory: ${{ inputs.tofu_directory }}
      id: plan
      run: tofu plan -input=false -lock=false -concise -no-color -out=./plan.tfplan
      shell: bash
      continue-on-error: true

    - uses: kishaningithub/setup-tf-summarize@v1
    
    - name: Convert Plan to JSON
      working-directory: ${{ inputs.tofu_directory }}
      id: plan_json
      run: |
        if [ -f "plan.tfplan" ]; then
          echo "Got Here"
          JSON_OUTPUT=$(tofu show -json ./plan.tfplan | tf-summarize )
          echo "json_output<<EOF" >> $GITHUB_OUTPUT
          echo "$JSON_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "json=json_output"
        else
          echo "json_output=Error: No Plan File Generated" >> $GITHUB_OUTPUT
        fi
      shell: bash
      continue-on-error: true
    
    - name: Parse Plan Summary
      working-directory: ${{ inputs.tofu_directory }}
      id: parse_plan
      run: |
        if [ -f "plan.tfplan" ]; then
          SUMMARY=$(tofu show plan.tfplan | head -20)
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        else
          echo "summary=No plan file generated" >> $GITHUB_OUTPUT
        fi
      shell: bash
      continue-on-error: true
    
    - name: Potential Failure        
      if: ${{ steps.init.outputs.stderr || steps.validate.outputs.stderr || steps.plan.outputs.stderr }}
      run: |
        echo "Errors found in Validation Or Plan. Failing the job."
        echo ${{ steps.validate.outputs.stderr || steps.plan.outputs.stderr }}
        exit 1
      shell: bash