name: Deploy code to GCP

on:
  #push:
  #  branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v4'

    - name: 'Authenticate with GCP'
      uses: './.github/actions/auth_to_gcp'
      with:
        gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        gcp_workload_pool: ${{ secrets.GCP_WORKLOAD_POOL }}
        gcp_workload_provider: ${{ secrets.GCP_WORKLOAD_PROVIDER }}